-- ==========================================
-- SECTOR: SEGURIDAD Y PERSONAL MÉDICO
-- ==========================================

CREATE TABLE USUARIO (
    PK_USUARIO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USUARIO VARCHAR2(50) NOT NULL UNIQUE,
    CONTRASENA VARCHAR2(100) NOT NULL,
    ESTADO VARCHAR2(50) NOT NULL
);

CREATE TABLE ESPECIALIDAD (
    PK_ESPECIALIDAD NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(200)
);

CREATE TABLE PERSONAL_MEDICO (
    PK_PERSONAL_MEDICO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FK_USUARIO NUMBER NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL,
    APELLIDO VARCHAR2(100) NOT NULL,
    SEG_APELLIDO VARCHAR2(100),
    CODIGO_MEDICO VARCHAR2(30) NOT NULL UNIQUE,
    CORREO_ELECTRONICO VARCHAR2(100) NOT NULL UNIQUE,
    TELEFONO VARCHAR2(20),
    ESTADO VARCHAR2(20) NOT NULL,

    CONSTRAINT FK_PERSONAL_USUARIO
        FOREIGN KEY (FK_USUARIO)
        REFERENCES USUARIO(PK_USUARIO)
);

CREATE TABLE MEDICO_ESPECIALIDAD (
    PK_MEDICO_ESPECIALIDAD NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FK_PERSONAL_MEDICO NUMBER NOT NULL,
    FK_ESPECIALIDAD NUMBER NOT NULL,

    CONSTRAINT FK_MEDICO_ESPECIALIDAD_PERSONAL
        FOREIGN KEY (FK_PERSONAL_MEDICO)
        REFERENCES PERSONAL_MEDICO(PK_PERSONAL_MEDICO),

    CONSTRAINT FK_MEDICO_ESPECIALIDAD_ESPECIALIDAD
        FOREIGN KEY (FK_ESPECIALIDAD)
        REFERENCES ESPECIALIDAD(PK_ESPECIALIDAD)
);

-- ==========================================
-- SECTOR: PACIENTES Y LOGÍSTICA
-- ==========================================

CREATE TABLE PACIENTE (
    PK_PACIENTE NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CEDULA VARCHAR2(20) NOT NULL UNIQUE,
    NOMBRE VARCHAR2(100) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    GENERO VARCHAR2(20),
    TELEFONO VARCHAR2(20),
    DIRECCION VARCHAR2(255)
);

CREATE TABLE CONSULTORIO (
    PK_CONSULTORIO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NUMERO_CONSULTORIO VARCHAR2(10) NOT NULL,
    LOCALIDAD VARCHAR2(50),
    PROVINCIA VARCHAR2(50)
);

CREATE TABLE CITA (
    PK_CITA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FK_PACIENTE NUMBER NOT NULL,
    FK_CONSULTORIO NUMBER NOT NULL,
    FECHA_HORA TIMESTAMP NOT NULL,
    DURACION VARCHAR2(20),
    ESTADO VARCHAR2(20),

    CONSTRAINT FK_CITA_PACIENTE
        FOREIGN KEY (FK_PACIENTE)
        REFERENCES PACIENTE(PK_PACIENTE),

    CONSTRAINT FK_CITA_CONSULTORIO
        FOREIGN KEY (FK_CONSULTORIO)
        REFERENCES CONSULTORIO(PK_CONSULTORIO)
);

-- ==========================================
-- SECTOR: EXPEDIENTE CLÍNICO
-- ==========================================

CREATE TABLE EXPEDIENTE (
    PK_EXPEDIENTE NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FK_PACIENTE NUMBER NOT NULL UNIQUE,
    FECHA_CREACION DATE NOT NULL,

    CONSTRAINT FK_EXPEDIENTE_PACIENTE
        FOREIGN KEY (FK_PACIENTE)
        REFERENCES PACIENTE(PK_PACIENTE)
);

CREATE TABLE DIAGNOSTICO (
    PK_DIAGNOSTICO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_CIE10 VARCHAR2(10) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR2(200) NOT NULL
);

CREATE TABLE CONSULTA (
    PK_CONSULTA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FK_EXPEDIENTE NUMBER NOT NULL,
    FK_PERSONAL_MEDICO NUMBER NOT NULL,
    FK_DIAGNOSTICO NUMBER NOT NULL,
    FK_CITA NUMBER NOT NULL,
    FECHA_CONSULTA DATE NOT NULL,
    MOTIVO VARCHAR2(200),
    OBSERVACIONES VARCHAR2(200),

    CONSTRAINT FK_CONSULTA_EXPEDIENTE
        FOREIGN KEY (FK_EXPEDIENTE)
        REFERENCES EXPEDIENTE(PK_EXPEDIENTE),

    CONSTRAINT FK_CONSULTA_MEDICO
        FOREIGN KEY (FK_PERSONAL_MEDICO)
        REFERENCES PERSONAL_MEDICO(PK_PERSONAL_MEDICO),

    CONSTRAINT FK_CONSULTA_DIAGNOSTICO
        FOREIGN KEY (FK_DIAGNOSTICO)
        REFERENCES DIAGNOSTICO(PK_DIAGNOSTICO),

    CONSTRAINT FK_CONSULTA_CITA
        FOREIGN KEY (FK_CITA)
        REFERENCES CITA(PK_CITA)
);

-- ==========================================
-- SECTOR: FARMACIA Y PRESCRIPCIONES
-- ==========================================

CREATE TABLE RECETAS (
    PK_RECETA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FK_CONSULTA NUMBER NOT NULL,
    FECHA_EMISION DATE NOT NULL,

    CONSTRAINT FK_RECETA_CONSULTA
        FOREIGN KEY (FK_CONSULTA)
        REFERENCES CONSULTA(PK_CONSULTA)
);

CREATE TABLE MEDICAMENTOS (
    PK_MEDICAMENTO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL
);

CREATE TABLE DETALLE_MEDICAMENTOS (
    PK_DETALLE_MEDICAMENTOS NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FK_MEDICAMENTO NUMBER NOT NULL,
    PRESENTACION VARCHAR2(100),
    CONCENTRACION VARCHAR2(50),
    ENTRADAS NUMBER DEFAULT 0,
    SALIDAS NUMBER DEFAULT 0,
    LOTES VARCHAR2(50),
    VENCIMIENTOS DATE,

    CONSTRAINT FK_DETALLE_MEDICAMENTO
        FOREIGN KEY (FK_MEDICAMENTO)
        REFERENCES MEDICAMENTOS(PK_MEDICAMENTO)
);

CREATE TABLE DETALLE_RECETA (
    PK_DETALLE_RECETA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FK_RECETA NUMBER NOT NULL,
    FK_MEDICAMENTOS NUMBER NOT NULL,
    DOSIS VARCHAR2(50),
    FRECUENCIA VARCHAR2(50),

    CONSTRAINT FK_DETALLE_RECETA_RECETA
        FOREIGN KEY (FK_RECETA)
        REFERENCES RECETAS(PK_RECETA),

    CONSTRAINT FK_DETALLE_RECETA_MEDICAMENTO
        FOREIGN KEY (FK_MEDICAMENTOS)
        REFERENCES MEDICAMENTOS(PK_MEDICAMENTO)
);



-- ==========================================
-- INSERT DE LAS TABLAS
-- ==========================================

-- USUARIO
INSERT INTO USUARIO (USUARIO, CONTRASENA, ESTADO)
VALUES ('admin','Admin123','ACTIVO');

INSERT INTO USUARIO (USUARIO, CONTRASENA, ESTADO)
VALUES ('doctor01','Doc123','ACTIVO');

INSERT INTO USUARIO (USUARIO, CONTRASENA, ESTADO)
VALUES ('doctor02','Doc456','ACTIVO');


-- ESPECIALIDAD
INSERT INTO ESPECIALIDAD (NOMBRE, DESCRIPCION)
VALUES ('Medicina General','Atención primaria');

INSERT INTO ESPECIALIDAD (NOMBRE, DESCRIPCION)
VALUES ('Pediatría','Atención infantil');

INSERT INTO ESPECIALIDAD (NOMBRE, DESCRIPCION)
VALUES ('Cardiología','Enfermedades del corazón');

INSERT INTO ESPECIALIDAD (NOMBRE, DESCRIPCION)
VALUES ('Dermatología','Enfermedades de la piel');


-- PERSONAL MEDICO
INSERT INTO PERSONAL_MEDICO (FK_USUARIO,NOMBRE,APELLIDO,SEG_APELLIDO,CODIGO_MEDICO,CORREO_ELECTRONICO,TELEFONO,ESTADO)
VALUES(2,'María','Rodríguez','Soto','MED001','maria@hospital.com','88881111','ACTIVO');

INSERT INTO PERSONAL_MEDICO (FK_USUARIO,NOMBRE,APELLIDO,SEG_APELLIDO,CODIGO_MEDICO,CORREO_ELECTRONICO,TELEFONO,ESTADO)
VALUES (3,'Carlos','Jiménez','Rojas','MED002','carlos@hospital.com','88882222','ACTIVO');


-- MEDICO ESPECIALIDAD
INSERT INTO MEDICO_ESPECIALIDAD (FK_PERSONAL_MEDICO,FK_ESPECIALIDAD)
VALUES (1,1);

INSERT INTO MEDICO_ESPECIALIDAD (FK_PERSONAL_MEDICO,FK_ESPECIALIDAD)
VALUES (2,3);


-- PACIENTE
INSERT INTO PACIENTE (CEDULA,NOMBRE,FECHA_NACIMIENTO,GENERO,TELEFONO,DIRECCION)
VALUES ('101110111','Juan Pérez',DATE '1995-03-15','M','88887777','San José');

INSERT INTO PACIENTE (CEDULA,NOMBRE,FECHA_NACIMIENTO,GENERO,TELEFONO,DIRECCION)
VALUES ('202220222','Ana Mora',DATE '2000-06-20','F','88886666','Cartago');

INSERT INTO PACIENTE (CEDULA,NOMBRE,FECHA_NACIMIENTO,GENERO,TELEFONO,DIRECCION)
VALUES ('303330333','Luis Solano',DATE '1988-11-02','M','88885555','Heredia');


-- CONSULTORIO
INSERT INTO CONSULTORIO (NUMERO_CONSULTORIO,LOCALIDAD,PROVINCIA)
VALUES ('101','Hospital Central','San José');

INSERT INTO CONSULTORIO (NUMERO_CONSULTORIO,LOCALIDAD,PROVINCIA)
VALUES ('202','Hospital México','San José');


-- CITA
INSERT INTO CITA (FK_PACIENTE,FK_CONSULTORIO,FECHA_HORA,DURACION,ESTADO)
VALUES (1,1, 
TO_TIMESTAMP('2026-08-10 09:00:00','YYYY-MM-DD HH24:MI:SS'), '30 min', 'PROGRAMADA');

INSERT INTO CITA (FK_PACIENTE,FK_CONSULTORIO,FECHA_HORA,DURACION,ESTADO)
VALUES (2,2,
TO_TIMESTAMP('2026-08-10 10:00:00','YYYY-MM-DD HH24:MI:SS'), '45 min', 'PROGRAMADA');


-- EXPEDIENTE
INSERT INTO EXPEDIENTE (FK_PACIENTE,FECHA_CREACION)
VALUES (1,SYSDATE);

INSERT INTO EXPEDIENTE (FK_PACIENTE,FECHA_CREACION)
VALUES (2,SYSDATE);

INSERT INTO EXPEDIENTE(FK_PACIENTE,FECHA_CREACION)
VALUES(3,SYSDATE);


-- DIAGNOSTICO
INSERT INTO DIAGNOSTICO(CODIGO_CIE10,DESCRIPCION)
VALUES('J00','Resfriado común');

INSERT INTO DIAGNOSTICO(CODIGO_CIE10,DESCRIPCION)
VALUES('I10','Hipertensión esencial');

INSERT INTO DIAGNOSTICO(CODIGO_CIE10,DESCRIPCION)
VALUES('E11','Diabetes tipo 2');


-- CONSULTA
INSERT INTO CONSULTA (FK_EXPEDIENTE,FK_PERSONAL_MEDICO,FK_DIAGNOSTICO,FK_CITA,FECHA_CONSULTA,MOTIVO,OBSERVACIONES)
VALUES (1,1,1,1,DATE '2026-08-10','Fiebre','Paciente estable');

INSERT INTO CONSULTA (FK_EXPEDIENTE,FK_PERSONAL_MEDICO,FK_DIAGNOSTICO,FK_CITA,FECHA_CONSULTA,MOTIVO,OBSERVACIONES)
VALUES (2,2,2,2,DATE '2026-08-10','Control','Presión elevada');


-- RECETAS
INSERT INTO RECETAS (FK_CONSULTA,FECHA_EMISION)
VALUES (1,SYSDATE);

INSERT INTO RECETAS (FK_CONSULTA,FECHA_EMISION)
VALUES (2,SYSDATE);


-- MEDICAMENTOS
INSERT INTO MEDICAMENTOS (NOMBRE)
VALUES ('Paracetamol');

INSERT INTO MEDICAMENTOS (NOMBRE)
VALUES ('Ibuprofeno');

INSERT INTO MEDICAMENTOS (NOMBRE)
VALUES ('Amoxicilina');


-- DETALLE MEDICAMENTOS
INSERT INTO DETALLE_MEDICAMENTOS (FK_MEDICAMENTO,PRESENTACION,CONCENTRACION,ENTRADAS,SALIDAS,LOTES,VENCIMIENTOS)
VALUES (1,'Tabletas','500 mg',100,5,'LOT001',DATE '2027-12-31');

INSERT INTO DETALLE_MEDICAMENTOS (FK_MEDICAMENTO,PRESENTACION,CONCENTRACION,ENTRADAS,SALIDAS,LOTES,VENCIMIENTOS)
VALUES (2,'Cápsulas','400 mg',150,10,'LOT002',DATE '2027-10-15');


-- DETALLE RECETA
INSERT INTO DETALLE_RECETA (FK_RECETA,FK_MEDICAMENTOS,DOSIS,FRECUENCIA)
VALUES (1,1,'1 tableta','Cada 8 horas');

INSERT INTO DETALLE_RECETA (FK_RECETA,FK_MEDICAMENTOS,DOSIS,FRECUENCIA)
VALUES (2,2,'1 cápsula','Cada 12 horas');

COMMIT;