# ==============================================================
# Configuracion de la aplicacion
# ==============================================================
# Aquí puedes dejar el nombre tal cual está, identifica tu proyecto.
spring.application.name=ExpedientesAPP
# El puerto 8080 está perfecto, es el puerto por defecto de Spring Boot.
server.port=8080

# Recargar plantillas Thymeleaf sin reiniciar (solo en dev)
spring.thymeleaf.cache=false

# ==============================================================
# Conexion a Oracle
# ==============================================================
spring.datasource.url=jdbc:oracle:thin:@bd01_high?TNS_ADMIN=C:/Wallet_BD01
spring.datasource.username=ProyectLenguaj
spring.datasource.password=PasswordSeguro123#
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ==============================================================
# JPA / Hibernate
# ==============================================================
# Hibernate crea o actualiza las tablas segun las @Entity
spring.jpa.hibernate.ddl-auto=update

# ¡OJO AQUÍ!: Como estás usando Oracle Cloud, cambia el Dialect al genérico moderno para evitar errores de compatibilidad
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# Ver el SQL generado en la consola (util en clase, NO en produccion)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==============================================================
# Logs
# ==============================================================
logging.level.root=INFO
logging.level.com.ufide.tiendaapp=DEBUG